# this build works with container based envs
sudo: false

language: scala

# need to keep this in step with build.sbt
scala:
  - 2.10.5
  - 2.11.6

# as of sept 2015 there is no "openjdk8"
jdk:
  - oraclejdk8
  
notifications:
  email:
    - brandon@bbrownsound.com